# Retail Performance Analytics

# SQL Analysis

In [1]:
import sqlite3

import pandas as pd

# Pandas display options
pd.set_option("display.max_columns", None)

## Load Clean Dataset

In [2]:
clean_df = pd.read_csv(
    "../data/processed/online_retail_clean.csv",
    dtype={
        "InvoiceNo": str,
        "StockCode": str
    },
    parse_dates=["InvoiceDate"]
)

#### Observation

The cleaned dataset created during the previous stage of the project is loaded into pandas before being imported into the SQLite database.

## Create SQLite Database

In [3]:
connection = sqlite3.connect(
    "../data/processed/retail.db"
)

#### Observation

A SQLite database is created to store the cleaned dataset and execute SQL queries throughout this notebook.

## Load Data into SQLite

In [5]:
rows_inserted = clean_df.to_sql(
    name="retail",
    con=connection,
    if_exists="replace",
    index=False
)

print(f"Rows inserted into SQLite: {rows_inserted:,}")

Rows inserted into SQLite: 525,460

#### Observation

The cleaned dataset is imported into a SQLite table named **retail**.

This table will be used for all SQL queries presented in this notebook.

## Validation

In [6]:
pd.read_sql(
    """
    SELECT *
    FROM retail
    LIMIT 5;
    """,
    connection
)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

#### Observation

The first rows confirm that the dataset was successfully loaded into the SQLite database and is ready for analysis.

In [7]:
pd.read_sql(
    """
    SELECT
        COUNT(*) AS TotalRows
    FROM retail;
    """,
    connection
)

   TotalRows
0     525460